# Generated by Django 5.0.3 on 2024-05-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=128)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('resumen', models.CharField(max_length=255)),
                ('fecha_entrada', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('disponible', models.BooleanField()),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.autor')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.categoria')),
                ('id_usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.usuario')),
            ],
        ),
    ]
