# Generated by Django 5.0.3 on 2024-05-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilersys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField()),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.plan')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.usuario')),
            ],
        ),
    ]
