# Generated by Django 5.0.3 on 2024-05-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilersys', '0003_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=128)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.rol')),
            ],
        ),
    ]
