# Generated by Django 5.0.3 on 2024-05-19 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilersys', '0007_alter_alquiler_id_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquilersys.usuario'),
            preserve_default=False,
        ),
    ]
