# Generated by Django 5.0.3 on 2024-05-19 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilersys', '0008_alquiler_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('valor', models.IntegerField(default=0)),
                ('id_alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.alquiler')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilersys.usuario')),
            ],
        ),
    ]
