# Generated by Django 5.0.3 on 2024-05-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilersys', '0009_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
