# Generated by Django 5.0.3 on 2024-05-20 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilersys', '0010_movimiento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='id_suscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alquilersys.suscripcion'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_alquiler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alquilersys.alquiler'),
        ),
    ]
